name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Only triggers production deployment on `main` branch

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'  # Ensure this only runs for the `main` branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21  

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel (Production)
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
